### ISSUE TITLE
一个小建议：能否开发一个分支，西文沿用Klee字体

### ISSUE THREAD

**Issue by ghost** [NoHeartPen/QiushuiShotai#1]
这款字体确实对日专非常友好，不用再像以前那样切一次Klee再切一次LXGW。
但西文和数字的风格不不统一总感觉很别扭，想问下作者能不能一个西文沿用Klee的分支。

**Comment by NoHeartPen** [comment]
很好的建议:)

替换英文和数字完全是出于个人的需要（写代码的时候喜欢看等宽字体），普通人可能不习惯这种风格，是我失策了。

另外，现在上传的字体严格来说也更像原项目的[LXGW Bright](https://github.com/lxgw/LxgwBright)分支——英文和数字被替换为了 Ysabeau，但[LXGW Bright](https://github.com/lxgw/LxgwBright)包含的字数比[LxgwWenKai](https://github.com/lxgw/LxgwWenKai)少，所以我才会使用[LxgwWenKai](https://github.com/lxgw/LxgwWenKai)制作。

之后会按照如下思路修改：

QiushuiShotai：[Klee](https://github.com/fontworks-fonts/Klee)：`KleeOne-SemiBold.ttf`，提供日文汉字字形和英文字形；[LxgwWenKai](https://github.com/lxgw/LxgwWenKai)：`LXGWWenKai-Regular.ttf`，提供中文简体字字形（这个就是你说的西文沿用 Klee 的分支，会放在名为 QiushuiShotai 的文件夹下面）
QiushuiShotai Bright：[Ysabeau](https://github.com/CatharsisFonts/Ysabeau)：`Ysabeau Office Medium.ttf`，提供西文字形；[Klee](https://github.com/fontworks-fonts/Klee)：`KleeOne-SemiBold.ttf`，提供日文汉字字形；[LxgwWenKai](https://github.com/lxgw/LxgwWenKai)：`LXGWWenKai-Regular.ttf`，提供中文简体字字形

（和 LXGW 的命名规则是一样的）

最后，风格不统一也有可能是我选择 Ysabeau 的字重时没有选好，导致英文和数字看起来会比汉字粗一点，后面会尝试调整下。

由于还有其他琐碎的工作需要完成（修改文档、修改字体名），可能要周末才会上传，好了的话会在 issue 通知（如果你打开了邮件通知的话，应该很快就会收到，就不用来回查看了）

**Comment by NoHeartPen** [comment]
更新了哈，西文沿用 Klee 的分支在 [QiushuiShotai](https://github.com/NoHeartPen/QiushuiShotai/tree/master/QiushuiShotai) 文件夹
