### ISSUE TITLE
Win11下无法加粗

### ISSUE THREAD

**Issue by IamQisir** [NoHeartPen/QiushuiShotai#2]
谢谢作者给大家带来这么好用的字体，可是我在使用过程中遇到了无法加粗的问题，其他的字体可以加粗，但「秋水书体」无法加粗。请问有什么解决方法吗？

**Comment by NoHeartPen** [comment]
嗯……我这边在 Word 和 Obsidian 上都测试了下，发现加粗是正常的：

![image](https://user-images.githubusercontent.com/79316356/199948654-6c8e7efa-8bb0-4622-ae71-9389d6ea8be0.png)


![image](https://user-images.githubusercontent.com/79316356/199945813-7a736ca0-7306-455b-9a16-a1a216d402ec.png)
（使用Markdown的`**`加粗语法）

方便说一下是在哪里遇到的问题么？

关于解决方法：

1 . 可能是没有粗体的字体文件导致的——因为我并不是字体设计师，只是拿了现成的 Klee 的粗体和霞鹜文楷的常规字体来制作秋水書体（Klee的常规太细了，和霞鹜文楷的常规放到一起非常违和）。如果有人制作了 Klee 的超级加粗版的话，我就能制作一个粗体的字体文件了，但目前似乎没有……
2. 可能是由于使用的字体合并工具导致的，可以看看 https://github.com/nowar-fonts/Warcraft-Font-Merger/issues/6 这里的方法，如果有效的话，我可以在之后发布的版本里改下指令

**Comment by IamQisir** [comment]
我是下载ttf文件之后直接放到系统的Fonts文件夹中，显示的效果很好，在WPS以及Typora中加粗均失效了。。。我也不太清楚这是怎么回事。我之前自己尝试制作字体符号的时候，即使是修改原先的符号，也可以正常显示粗体。我下载的「秋水书体」和「Fusion Kai J」都出现了这个问题，但是其他字体就可以正常加粗。

**Comment by IamQisir** [comment]
作者！！！我发现了「秋水书体 Bright」可以加粗欸！ 但是「秋水书体」在我的电脑上是无法加粗的！终于解决啦！！！十分感谢哦 ! : D　 どうもありがとうございました！
